# Generated by Django 2.1.5 on 2019-01-24 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='specjalizacja',
            old_name='jarski',
            new_name='dzieci',
        ),
    ]
