# Generated by Django 2.1.5 on 2019-01-30 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('przychodnia', '0002_auto_20190124_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='Godziny',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nazwa', models.CharField(max_length=30, verbose_name='godziny')),
                ('godzina', models.DateField(help_text='Zaznacz, jeżeli składnik jest odpowiedni dla dzieci', verbose_name='Dodaj godzine')),
                ('lekarz', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='godziny', to='przychodnia.Lekarz')),
            ],
        ),
    ]
